# Generated by Django 5.2.7 on 2025-12-29 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("enrollment_date", models.DateField()),
                ("current_juz", models.PositiveSmallIntegerField(default=1)),
                ("total_juz_memorized", models.PositiveSmallIntegerField(default=0)),
                ("goal_juz", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("goal_date", models.DateField(blank=True, null=True)),
                ("challenges", models.TextField(blank=True, null=True)),
                ("last_milestone_juz", models.PositiveSmallIntegerField(default=0)),
                ("muraja_only_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "student",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "teacher",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="MurajaSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("muraja_juz_per_day", models.FloatField(default=1)),
                ("cycle_length_days", models.PositiveSmallIntegerField(default=7)),
                ("next_revision_due_date", models.DateField(blank=True, null=True)),
                ("overdue", models.BooleanField(default=False)),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "db_table": "muraja_schedule",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DailyLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("FRONT_REVISION", "FRONT_REVISION"),
                            ("MURAJAH", "MURAJAH"),
                        ],
                        max_length=20,
                    ),
                ),
                ("juz", models.PositiveSmallIntegerField()),
                ("surah", models.CharField(max_length=255)),
                ("ayah_start", models.PositiveSmallIntegerField()),
                ("ayah_end", models.PositiveSmallIntegerField()),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("Pass", "Pass"),
                            ("Re-do", "Re-do"),
                            ("Absent", "Absent"),
                            ("Not Ready", "Not Ready"),
                        ],
                        max_length=20,
                    ),
                ),
                ("extra_work", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "db_table": "daily_lesson",
                "ordering": ["-date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("Quarterly", "Quarterly"), ("Test", "Test")],
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "db_table": "assessment",
                "ordering": ["-date", "id"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.teacher",
            ),
        ),
        migrations.CreateModel(
            name="MonthlyPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.CharField(max_length=7)),
                ("new_work_points", models.PositiveSmallIntegerField(default=0)),
                ("front_work_points", models.PositiveSmallIntegerField(default=0)),
                ("back_work_points", models.PositiveSmallIntegerField(default=0)),
                ("extra_work_points", models.PositiveSmallIntegerField(default=0)),
                ("attendance_points", models.PositiveSmallIntegerField(default=0)),
                ("behavior_points", models.PositiveSmallIntegerField(default=0)),
                ("total_points", models.PositiveSmallIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "db_table": "monthly_points",
                "ordering": ["month", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "month"),
                        name="uniq_monthly_points_student_month",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("passed", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "db_table": "homework",
                "ordering": ["-date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date"), name="uniq_homework_student_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("present", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "ordering": ["-date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date"), name="uniq_attendance_student_date"
                    )
                ],
            },
        ),
    ]
